# Generated by Django 3.1.5 on 2022-04-14 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugs', models.CharField(max_length=264, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('refill', models.CharField(choices=[('No refill', 'No refill'), ('One time', 'One time'), ('Two time', 'Two time'), ('Three time', 'Three time'), ('Four time', 'Four time'), ('Five time', 'Five time'), ('Six time', 'Six time')], max_length=264, null=True)),
                ('void_after', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_scan', models.CharField(choices=[('Pathology', 'Pathology'), ('Radiology', 'Radiology'), ('Hermatology', 'Hermatology'), ('Prescription', 'Prescription')], max_length=264, null=True)),
                ('report_name', models.CharField(max_length=264, null=True)),
                ('ref_doctors', models.CharField(max_length=264, null=True)),
                ('date', models.DateField(null=True)),
                ('file', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='X_Ray_Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_x_ray', models.CharField(choices=[('Chest', 'Chest'), ('Knee', 'Knee'), ('Arm', 'Arm'), ('Shoulder', 'Shoulder'), ('Brain', 'Brain')], max_length=264, null=True)),
                ('ref_doctors', models.CharField(max_length=264, null=True)),
                ('code_ID', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264, null=True)),
                ('last_name', models.CharField(max_length=264, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=264, null=True)),
                ('address', models.CharField(max_length=264, null=True)),
                ('state', models.CharField(max_length=264, null=True)),
                ('city', models.CharField(max_length=264, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
