# Generated by Django 3.1.5 on 2022-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='scan_report',
            name='file',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
